name: Build and publish to Azure

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: acrcontainerdemox.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build dotnetapp -t acrcontainerdemox.azurecr.io/dotnetapp:${{ github.sha }}
        docker push acrcontainerdemox.azurecr.io/dotnetapp:${{ github.sha }}

    - uses: azure/appservice-settings@v1
      with:
        app-name: 'app-container-demo'
        app-settings-json: '[{"name": "ASPNETCORE_ENVIRONMENT", "value": "Production"}]'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-container-demo'
        images: 'acrcontainerdemox.azurecr.io/dotnetapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout